starting_url = ""
sitemap_xml_file_path = ""
url_list = []
parent_urls = []
crawl_depth = 6
url_tree = {}
urls_tocrawl = 100
child_nodes = 10
subdom_exclud =['/burgenland.','/sport.','/wetter.','/ooe.']